---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/config-file/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - SQL
DISABLE_LINTERS:
  - JAVASCRIPT_ES
  - JAVASCRIPT_PRETTIER
  - RUBY_RUBOCOP
  - REPOSITORY_CHECKOV
  - REPOSITORY_TRIVY
  - REPOSITORY_KICS
  - SPELL_VALE
  - SPELL_LYCHEE
  - SPELL_PROSELINT
  - GO_REVIVE
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  # TEMPORARY DISABLE waiting megalinter to support go 1.23
  - GO_GOLANGCI_LINT
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
EXCLUDED_DIRECTORIES:
  - ".history"
  - ".git"
  - ".idea"
  - "bin"
  - "logs"
  - "node_modules"
  - "vendor"
FILTER_REGEX_EXCLUDE: |
  (?x)(
    \.git/|
    \.history/|
    \.idea/|
    ^bin/|
    ^logs/|
    ^vendor/|
    ^node_modules/
  )
FILEIO_REPORTER: false
PRE_COMMANDS:
  - command: go env -w GOTOOLCHAIN=go1.23.1+auto
    cwd: "workspace"
  - command: yarn add --dev eslint-plugin-json eslint-config-prettier
    cwd: "workspace"
POST_COMMANDS:
  # FIX files set as root user
  # HOST_USER_ID and HOST_GROUP_ID set in package.json
  - command: |
      if [[ "${CI_MODE:0}" = "0" && "{HOST_USER_ID:-0}" != "0" && "{HOST_GROUP_ID:-0}" != "0" ]]; then
        find . -user 0 -exec chown ${HOST_USER_ID}:${HOST_GROUP_ID} {} ';'
      fi
    cwd: "workspace"

  # remove files generated by cspell
  - command: find . -name '*megalinter_file_names_cspell.txt' -delete
    cwd: "workspace"

PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true

# Linters configurations
BASH_SHELLCHECK_FILTER_REGEX_EXCLUDE: |
  (?x)(
    ^vendor/|
    ^bin/|
    ^logs/|
    /testsData/
  )
BASH_SHELLCHECK_ARGUMENTS: --source-path=/tmp/lint
BASH_SHFMT_ARGUMENTS: -i 2 -ci

REPOSITORY_SECRETLINT_CONFIG_FILE: .secretlintrc.yml

EDITORCONFIG_EDITORCONFIG_CHECKER_FILTER_REGEX_EXCLUDE: |
  (?x)(
    \.git/|
    /(testdata|testsData)/.*\.(txt|help)|
    \.md$|
    ^.*-megalinter_file_names_cspell.txt
  )

GIT_GIT_DIFF_PRE_COMMANDS:
  - command: git config --global --add safe.directory /tmp/lint/.git
    continue_if_failed: false
  - command: git config --global core.autocrlf false
    continue_if_failed: false
  - command: git config --global core.eol lf
    continue_if_failed: false
  - command: git config --global core.whitespace cr-at-eol,-trailing-space
    continue_if_failed: false
  - command: git config --global core.excludesfile .gitignore
    continue_if_failed: false
  - command: git config --global apply.whitespace fix
    continue_if_failed: false
  - command: git config --global --add safe.directory .git
    continue_if_failed: false

IGNORE_GITIGNORED_FILES: true
IGNORE_GENERATED_FILES: true

JAVASCRIPT_DEFAULT_STYLE: prettier
JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
JAVASCRIPT_ES_FILTER_REGEX_EXCLUDE: (report/)

JSON_ESLINT_PLUGIN_JSONC_FILE_NAME: .eslintrc.js

JSON_JSONLINT_FILTER_REGEX_EXCLUDE: |
  (?x)(
    \.vscode/.*\.json$
  )

SPELL_CSPELL_CONFIG_FILE: cspell.yaml
SPELL_CSPELL_FILTER_REGEX_EXCLUDE: |
  (?x)(
    \.git/|
    ^\.history/|
    IDE/.*/\.idea|
    ^.*-megalinter_file_names_cspell.txt|
    ^megalinter-reports/|
    ^pages/README.md|
    ^commit-msg.md$|
    /testsData/|
    \.svg$
  )
SPELL_FILTER_REGEX_EXCLUDE: |
  (?x)(
    \.git/|
    \.history/|
    IDE/.*/\.idea|
    \.svg
  )

MARKDOWN_MARKDOWN_LINK_CHECK_FILTER_REGEX_EXCLUDE: |
  (?x)(
    ^pages/README.md|
    ^pages/_sidebar.md
  )

ACTION_ACTIONLINT_FILTER_REGEX_EXCLUDE: |
  (?x)(
    ^\.github/workflows/dependabot\.yml$
  )

YAML_V8R_FILTER_REGEX_EXCLUDE: |
  (?x)(
    ^\.vscode/.*$|
    ^\.github/workflows/dependabot\.yml$|
    ^\.secretlintrc\.yml$|
    ^\.secretlintrc\.json$|
    /testsData/.*\.yaml$|
    ^\.grype\.yaml$|
    ^\.checkov\.yaml$|
    ^\.trivy\.yaml
  )

YAML_V8R_DISABLE_ERRORS_IF_LESS_THAN: 5

MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: |
  (?x)(
    ^pages/README.md|
    ^pages/doc|
    ^pages/tests
  )

GO_GOLANGCI_LINT_CLI_LINT_MODE: project # will remove the list of files as arguments and run the linter with root workspace cwd
GO_GOLANGCI_LINT_ARGUMENTS:
  ["--go", "1.23.1", "--out-format", "sarif", "--verbose", "./..."]
LOG_LEVEL: DEBUG # will show you the exact command run

REPOSITORY_DEVSKIM_ARGUMENTS:
  ["analyze", "--file-format", "sarif", "--skip-git-ignored-files"]
