---
###########################################
# These are the rules used for            #
# linting all the yaml files in the stack #
# NOTE:                                   #
# You can disable line with:              #
# # yamllint disable-line                 #
###########################################
extends: default
rules:
  truthy:
    allowed-values:
      - "true"
      - "false"
      - "on"
      - "off"
    check-keys: true
  indentation:
    spaces: consistent
  new-lines:
    level: warning
    type: unix
  line-length:
    max: 500
  comments:
    min-spaces-from-content: 1 # Used to follow prettier standard: https://github.com/prettier/prettier/pull/10926
